sudo: required
services:
  - docker

before_install:
  - docker build -t tarassarmat/docker-react -f Dockerfile.dev .

script:
  - docker run tarassarmat/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker'
  env: 'Docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-930061976945'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
